name: MAKE THE LOGO SMALLER
favicon: null
layout_spectrum: 0.8441296787932515
typography_spectrum: 0.5748130832798779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5298827604856342
  lightness: 0.5973680969327688
  saturation: 0.8227517972700298
  rhythmicContrast: 0.06986126280389726
purpose: []
