title: Years of breaking and making things
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8227517972700298
  brandStrength: 0.5298827604856342
  rhythmicContrast: 0.06986126280389726
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#999999'
    - '#6a6a6a'
    - '#414141'
  lightness: 0.5973680969327688
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: MAKE THE LOGO SMALLER
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5748130832798779
layout_spectrum: 0.05017921
